name: flavored_env
description: A utility to generate matching dotenv and dart configuration files.
version: 0.5.0
homepage: https://github.com/berbsd/flavored_env
repository: https://github.com/berbsd/flavored_env.git

executable:
  flavored_env:

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  args: ^2.3.0
  dart_style: ^2.2.3
  mason_logger: ^0.1.0-dev.7
  meta: ^1.7.0
  path: ^1.8.1
  recase: ^4.0.0
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.1.10
  build_version: ^2.1.1
  mocktail: ^0.2.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0
