name: flavored_env

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v3

      - name: 🎯 Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: 📦 Install Dependencies
        run: dart pub get
        
      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: ✨ Check Formatting
      # run: dart format --output=none --set-exit-if-changed .

#       - name: 🕵️ Analyze
#         run: dart analyze lib
#         run: dart analyze --fatal-infos --fatal-warnings lib

      - name: 🧪 Run Tests
        run: |
          pub global activate test_coverage
          export PATH=$PATH:$HOME/.pub-cache/bin
          test_coverage
      - name: 📊 Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1
        with:
          path: ./coverage/lcov.info
          min_coverage: 80

